[package]
name = "girafe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
femtovg = "0.8.0"
hound = "3.5.1"
whisper-rs = "0.8.0"
winit = "0.29.3"
glutin = "0.30.10"
cpal = "0.15.2"
